query {
    result: EnjinSearch(
        term: $term
        pagination: $pagination
    ) {
        ... on EnjinApp {
            appId: id
        }
        ... on EnjinIdentity {
            identityId: id
        }
        ... on EnjinToken {
            tokenId: id
        }
        ... on EnjinTransaction {
            requestId: id
        }
        ... on EnjinUser {
            userId: id
        }
    }
}

$term: String!
$pagination: PaginationInput
