mutation {
    result: UpdateEnjinUser(
        id: $id,
        name: $name,
        email: $email,
        password: $password,
        identity_id: $identityId,
        roles: $roles,
        reset_password: $resetPassword,
        reset_password_token: $resetPasswordToken
    ) {
        ...UserFragment
    }
}

$id: Int
$name: String
$email: String
$password: String
$identityId: Int
$roles: [String]
$resetPassword: Boolean
$resetPasswordToken: String