extends Reference
class_name TransactionType

const APPROVE: String = "APPROVE"
const CREATE: String = "CREATE"
const MINT: String = "MINT"
const SEND: String = "SEND"
const SEND_ENJ: String = "SEND_ENJ"
const ADVANCED_SEND: String = "ADVANCED_SEND"
const CREATE_TRADE: String = "CREATE_TRADE"
const COMPLETE_TRADE: String = "COMPLETE_TRADE"
const CANCEL_TRADE: String = "CANCEL_TRADE"
const MELT: String = "MELT"
const UPDATE_NAME: String = "UPDATE_NAME"
const SET_ITEM_URI: String = "SET_ITEM_URI"
const SET_WHITELISTED: String = "SET_WHITELISTED"
const SET_TRANSFERABLE: String = "SET_TRANSFERABLE"
const SET_MELT_FEE: String = "SET_MELT_FEE"
const DECREASE_MAX_MELT_FEE: String = "DECREASE_MAX_MELT_FEE"
const SET_TRANSFER_FEE: String = "SET_TRANSFER_FEE"
const DECREASE_MAX_TRANSFER_FEE: String = "DECREASE_MAX_TRANSFER_FEE"
const RELEASE_RESERVE: String = "RELEASE_RESERVE"
const ADD_LOG: String = "ADD_LOG"
const SET_APPROVAL_FOR_ALL: String = "SET_APPROVAL_FOR_ALL"
const MANAGER_UPDATE: String = "MANAGER_UPDATE"
const SET_DECIMALS: String = "SET_DECIMALS"
const SET_SYMBOL: String = "SET_SYMBOL"
const MESSAGE: String = "MESSAGE"
