query {
    result: EnjinBalances(
        appId: $appId,
        tokenId: $tokenId,
        value: $value,
        value_gt: $valGt,
        value_gte: $valGte,
        value_lt: $valLt,
        value_lte: $valLte
    ) {
        ...BalanceFragment
    }
}

$appId: Int
$tokenId: String
$value: Int
$valGt: Int
$valGte: Int
$valLt: Int
$valLte: Int